name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for changelog generation
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        vs-version: '[17.0,18.0)'
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: Echo Directory Structure Before Build
      shell: pwsh
      run: |
        Write-Host "Current Directory Structure:"
        Get-ChildItem -Recurse | Select-Object FullName
      
    - name: Restore NuGet packages
      run: nuget restore WelcomeScreenCustomizer.sln
      
    - name: Build Solution
      shell: pwsh
      run: |
        msbuild WelcomeScreenCustomizer.sln `
          /p:Configuration=Release `
          /p:Platform="Any CPU" `
          /p:OutputPath=".\bin\Release" `
          /p:OutDir=".\bin\Release" `
          /t:Rebuild `
          /p:DebugSymbols=false `
          /p:DebugType=None `
          /verbosity:detailed
      
    - name: Echo Build Output Directory
      shell: pwsh
      run: |
        Write-Host "Build Output Directory Structure:"
        Get-ChildItem -Path ".\bin\Release" -Recurse | Select-Object FullName
      
    - name: Create Release Package
      shell: pwsh
      run: |
        # Create release directory
        New-Item -ItemType Directory -Force -Path ".\ReleasePackage"
        
        # Find and copy the executable
        $exePath = Get-ChildItem -Path ".\bin\Release" -Filter "WelcomeScreenCustomizer.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        if (-not $exePath) {
            Write-Error "Could not find WelcomeScreenCustomizer.exe in the build output"
            exit 1
        }
        Write-Host "Found executable at: $exePath"
        
        # Copy executable to release package and standalone location
        Copy-Item $exePath -Destination ".\ReleasePackage\"
        Copy-Item $exePath -Destination ".\WelcomeScreenCustomizer.exe"
        
        # Copy documentation
        Copy-Item ".\README.md" -Destination ".\ReleasePackage\"
        
        # List contents before creating ZIP
        Write-Host "Release Package Contents:"
        Get-ChildItem -Path ".\ReleasePackage" -Recurse
        
        # Create ZIP file
        Compress-Archive -Path ".\ReleasePackage\*" -DestinationPath "WelcomeScreenCustomizer.zip" -Force

    - name: Generate Release Notes
      id: release_notes
      shell: pwsh
      run: |
        # Get the current tag
        $currentTag = "${{ github.ref_name }}"
        
        # Get the previous tag
        $previousTag = $(git describe --tags --abbrev=0 "${{ github.ref_name }}^" 2>$null)
        
        # Generate changelog
        $changelog = if ($previousTag) {
            git log --pretty=format:"- %s" "$previousTag..$currentTag"
        } else {
            git log --pretty=format:"- %s" "$currentTag"
        }
        
        # Create release notes content
        $releaseNotes = @"
        # Windows 11 Welcome Screen Customizer $currentTag
        
        ## Changes in this version:
        $changelog
        
        ## Downloads
        - **WelcomeScreenCustomizer.zip** - Full package with documentation
        - **WelcomeScreenCustomizer.exe** - Standalone executable
        
        ## Package Contents
        - WelcomeScreenCustomizer.exe (Main application with embedded icon)
        - README.md (Documentation)
        
        ## Important Notes
        - This application requires administrative privileges
        - Preventing OS override is required for the changes to persist
        - Compatible with Windows 11 only
        - The application is now fully portable - no additional files needed!
        
        ## Installation
        ### Option 1: ZIP Package
        1. Download and extract WelcomeScreenCustomizer.zip
        2. Run WelcomeScreenCustomizer.exe as administrator
        3. Follow the in-app instructions
        
        ### Option 2: Standalone Executable
        1. Download WelcomeScreenCustomizer.exe
        2. Run as administrator
        3. Follow the in-app instructions
        "@
        
        # Save release notes to file
        $releaseNotes | Out-File -FilePath release_notes.md -Encoding UTF8
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          WelcomeScreenCustomizer.zip
          WelcomeScreenCustomizer.exe
        draft: false
        prerelease: false
        generate_release_notes: true
        body_path: release_notes.md
